/* Autogenerated by png2wx.pl on Sat Dec 14 08:45:42 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_launcher_pi;
extern wxBitmap *_img_launcher;

#endif /* ICONS_H */
